### ISSUE TITLE
Site URL issue?

### ISSUE THREAD

**Issue by seabits-steve** [ghostboard/ghost-purge-images#1]
I'm trying to use ghost-purge-images to clean up a test site, and am getting the following error:

ghost-purge-images display key=XXX
url https://ghost.sailbits.comghost/api/v2/content/settings/?key=XXX
❌ Error: Error: getaddrinfo ENOTFOUND ghost.sailbits.comghost ghost.sailbits.comghost:443

Note that I've replaced my key with XXX but am using a normal key.

The site URL is https://ghost.sailbits.com/ but for some reason it is adding a "ghost" in the middle of the hostname.

**Comment by Maxszik** [comment]
- I'm having exactly the same issue.

**Comment by dburgos** [comment]
A fix is available:
1 - Please update to the latest version 2.0.3 running `npm i -g ghost-purge-images`
2 - Then try again with `ghost-purge-images display key=XXX`

![ghost-purge-images-issue-1](https://user-images.githubusercontent.com/1589874/53106378-388ed600-3533-11e9-9c05-7b3f354b25ef.jpg)

Sorry for the inconvenience and thanks for your patience 👍

**Comment by Maxszik** [comment]
Still not working, comrade. Installing is fine, running the display command is good, but when trying to do the actual purging I get
`❌ content/images/2019/02/toshkent-logo-en_o.png
 Error:Error: EACCES: permission denied, unlink 'content/images/2019/02/toshkent-logo-en_o.png'
❌ content/images/2019/02/tran-station-dog_o.jpg
 Error:Error: EACCES: permission denied, unlink 'content/images/2019/02/tran-station-dog_o.jpg'
❌ content/images/2019/02/trans-siberian-crew_o.jpg
 Error:Error: EACCES: permission denied, unlink 'content/images/2019/02/trans-siberian-crew_o.jpg'
❌ content/images/2019/02/transsib-crew_o.jpg
 Error:Error: EACCES: permission denied, unlink 'content/images/2019/02/transsib-crew_o.jpg'
❌ content/images/2019/02/vereshyagin_o.jpg
 Error:Error: EACCES: permission denied, unlink 'content/images/2019/02/vereshyagin_o.jpg'
❌ content/images/2019/02/volgo-don_o.jpg
 Error:Error: EACCES: permission denied, unlink 'content/images/2019/02/volgo-don_o.jpg'
❌ content/images/2019/02/we-sail-at-night_o.jpg
 Error:Error: EACCES: permission denied, unlink 'content/images/2019/02/we-sail-at-night_o.jpg'

📊 Summary:
- 0 files removed
- Saved space: 0.00MB

🎁 Open source tool by David Burgos from https://ghostboard.io
ghost-mgr@ghost-caucasusandmercury:/var/www/ghost$ `

**Comment by dburgos** [comment]
@Caucasus-and-Mercury It looks like another issue related to files permission in your server, but not the tool itself.
Please try:
- Give permissions to the content folder: `chown -R yourUsername ./content/* ` (change `yourUsername` with the name of your server user)
- Installing with `sudo npm i -g ghost-purge-images --unsafe-perm=true --allow-root`
